export const events = [
  {
    id: 1,
    title: 'React Native Workshop',
    image: 'https://picsum.photos/600/400?random=1',
    category: 'Workshop',
    date: '2025-07-01',
    description: 'Hands-on session covering the basics of React Native development.',
  },
  {
    id: 2,
    title: 'AI in Education Seminar',
    image: 'https://picsum.photos/600/400?random=2',
    category: 'Seminar',
    date: '2025-07-02',
    description: 'Explore how AI is transforming modern education.',
  },
  {
    id: 3,
    title: 'Campus Cricket Tournament',
    image: 'https://picsum.photos/600/400?random=3',
    category: 'Sports',
    date: '2025-07-03',
    description: 'Join the cricket fever with teams across departments!',
  },
  {
    id: 4,
    title: 'Cyber Security Bootcamp',
    image: 'https://picsum.photos/600/400?random=4',
    category: 'Workshop',
    date: '2025-07-04',
    description: 'Learn how to protect your digital footprint.',
  },
  {
    id: 5,
    title: 'Photography Competition',
    image: 'https://picsum.photos/600/400?random=5',
    category: 'Contest',
    date: '2025-07-05',
    description: 'Capture the campus beauty and win exciting prizes!',
  },
  {
    id: 6,
    title: 'Design Thinking Workshop',
    image: 'https://picsum.photos/600/400?random=6',
    category: 'Workshop',
    date: '2025-07-06',
    description: 'Creative problem-solving bootcamp for designers.',
  },
  {
    id: 7,
    title: 'E-Sports Gaming Night',
    image: 'https://picsum.photos/600/400?random=7',
    category: 'Entertainment',
    date: '2025-07-07',
    description: 'Join friends for a thrilling LAN party showdown.',
  },
  {
    id: 8,
    title: 'Web Development Hackathon',
    image: 'https://picsum.photos/600/400?random=8',
    category: 'Hackathon',
    date: '2025-07-08',
    description: 'Build websites in 24 hours – show off your skills!',
  },
  {
    id: 9,
    title: 'Startup Pitch Event',
    image: 'https://picsum.photos/600/400?random=9',
    category: 'Business',
    date: '2025-07-09',
    description: 'Pitch your startup idea to real investors!',
  },
  {
    id: 10,
    title: 'Mental Health Awareness Walk',
    image: 'https://picsum.photos/600/400?random=10',
    category: 'Awareness',
    date: '2025-07-10',
    description: 'Promote well-being through a mindful walk.',
  },
  {
    id: 11,
    title: 'Cultural Festival Day',
    image: 'https://picsum.photos/600/400?random=11',
    category: 'Cultural',
    date: '2025-07-11',
    description: 'Celebrate cultural diversity with food and dance.',
  },
  {
    id: 12,
    title: 'Drama Night – Open Mic',
    image: 'https://picsum.photos/600/400?random=12',
    category: 'Drama',
    date: '2025-07-12',
    description: 'Show your acting talent in a fun drama night.',
  },
  {
    id: 13,
    title: 'Python Programming Basics',
    image: 'https://picsum.photos/600/400?random=13',
    category: 'Tech',
    date: '2025-07-13',
    description: 'Begin your coding journey with Python fundamentals.',
  },
  {
    id: 14,
    title: 'Public Speaking Contest',
    image: 'https://picsum.photos/600/400?random=14',
    category: 'Contest',
    date: '2025-07-14',
    description: 'Deliver your best speech and impress the crowd.',
  },
  {
    id: 15,
    title: 'Volunteer Clean-Up Drive',
    image: 'https://picsum.photos/600/400?random=15',
    category: 'Community',
    date: '2025-07-15',
    description: 'Help keep the campus clean and green!',
  },
  {
    id: 16,
    title: 'Robotics Expo 2025',
    image: 'https://picsum.photos/600/400?random=16',
    category: 'Tech',
    date: '2025-07-16',
    description: 'Explore the latest innovations in robotics.',
  },
  {
    id: 17,
    title: 'AI vs Human Debate',
    image: 'https://picsum.photos/600/400?random=17',
    category: 'Debate',
    date: '2025-07-17',
    description: 'Discuss the future of AI and job automation.',
  },
  {
    id: 18,
    title: 'Mathematics Olympiad',
    image: 'https://picsum.photos/600/400?random=18',
    category: 'Academic',
    date: '2025-07-18',
    description: 'Challenge your math skills with campus-wide participants.',
  },
  {
    id: 19,
    title: 'Blockchain Technology Talk',
    image: 'https://picsum.photos/600/400?random=19',
    category: 'Seminar',
    date: '2025-07-19',
    description: 'Learn how blockchain is revolutionizing industries.',
  },
  {
    id: 20,
    title: 'Chess Masters Tournament',
    image: 'https://picsum.photos/600/400?random=20',
    category: 'Sports',
    date: '2025-07-20',
    description: 'Join the intellectual battle of chess minds!',
  },
];
